import { Activity, AlertCircle, CheckCircle2, Clock } from "lucide-react";
import { Patient } from "./types";

export const patientsData: Patient[] = [
  {
    id: "P001",
    name: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    phone: "+1 (555) 123-4567",
    age: 34,
    gender: "Female",
    status: "Active",
    lastVisit: "2024-03-10",
    nextAppointment: "2024-04-15",
    address: "123 Main St, City, State 12345",
    department: "Cardiology",
    conditions: ["Hypertension", "Diabetes"],
    medications: ["Lisinopril", "Metformin"],
    bloodType: "O+",
  },
  {
    id: "P002",
    name: "Michael Chen",
    email: "michael.chen@email.com",
    phone: "+1 (555) 234-5678",
    age: 45,
    gender: "Male",
    status: "Active",
    lastVisit: "2024-03-12",
    nextAppointment: "2024-03-25",
    address: "456 Oak Ave, City, State 12345",
    department: "Neurology",
    conditions: ["Migraines"],
    medications: ["Sumatriptan", "Propranolol"],
    bloodType: "A+",
  },
  {
    id: "P003",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@email.com",
    phone: "+1 (555) 345-6789",
    age: 28,
    gender: "Female",
    status: "Active",
    lastVisit: "2024-03-08",
    nextAppointment: "2024-04-01",
    address: "789 Pine Rd, City, State 12345",
    department: "Pediatrics",
    conditions: ["Asthma"],
    medications: ["Albuterol"],
    bloodType: "B+",
  },
  {
    id: "P004",
    name: "James Wilson",
    email: "james.wilson@email.com",
    phone: "+1 (555) 456-7890",
    age: 52,
    gender: "Male",
    status: "At Risk",
    lastVisit: "2024-02-28",
    nextAppointment: "2024-03-22",
    address: "321 Elm St, City, State 12345",
    department: "Orthopedics",
    conditions: ["Arthritis", "Back Pain"],
    medications: ["Ibuprofen", "Gabapentin"],
    bloodType: "A-",
  },
  {
    id: "P005",
    name: "Jessica Davis",
    email: "jessica.davis@email.com",
    phone: "+1 (555) 567-8901",
    age: 38,
    gender: "Female",
    status: "Active",
    lastVisit: "2024-03-11",
    nextAppointment: "2024-03-28",
    address: "654 Maple Dr, City, State 12345",
    department: "Dermatology",
    conditions: ["Eczema"],
    medications: ["Hydrocortisone"],
    bloodType: "O-",
  },
  {
    id: "P006",
    name: "Robert Martinez",
    email: "robert.martinez@email.com",
    phone: "+1 (555) 678-9012",
    age: 55,
    gender: "Male",
    status: "Inactive",
    lastVisit: "2024-01-15",
    nextAppointment: "2024-04-10",
    address: "987 Cedar Ln, City, State 12345",
    department: "Cardiology",
    conditions: ["High Cholesterol"],
    medications: ["Atorvastatin"],
    bloodType: "B-",
  },
  {
    id: "P007",
    name: "Amanda Brown",
    email: "amanda.brown@email.com",
    phone: "+1 (555) 789-0123",
    age: 31,
    gender: "Female",
    status: "Active",
    lastVisit: "2024-03-09",
    nextAppointment: "2024-03-23",
    address: "147 Birch Way, City, State 12345",
    department: "Neurology",
    conditions: [],
    medications: ["Vitamins"],
    bloodType: "AB+",
  },
  {
    id: "P008",
    name: "Christopher Lee",
    email: "christopher.lee@email.com",
    phone: "+1 (555) 890-1234",
    age: 42,
    gender: "Male",
    status: "Active",
    lastVisit: "2024-03-13",
    nextAppointment: "2024-04-05",
    address: "258 Spruce St, City, State 12345",
    department: "Orthopedics",
    conditions: ["Knee Pain"],
    medications: ["Physical Therapy"],
    bloodType: "O+",
  },
];

export const weeklyActivePatients = [
  { day: "Mon", patients: 340, appointments: 42 },
  { day: "Tue", patients: 380, appointments: 51 },
  { day: "Wed", patients: 420, appointments: 58 },
  { day: "Thu", patients: 410, appointments: 55 },
  { day: "Fri", patients: 450, appointments: 62 },
  { day: "Sat", patients: 380, appointments: 48 },
  { day: "Sun", patients: 300, appointments: 35 },
];

export const appointmentTrendData = [
  { week: "Week 1", completed: 140, pending: 35, cancelled: 15 },
  { week: "Week 2", completed: 155, pending: 32, cancelled: 13 },
  { week: "Week 3", completed: 168, pending: 28, cancelled: 14 },
  { week: "Week 4", completed: 172, pending: 25, cancelled: 11 },
];

export const recentActivities = [
  {
    id: 1,
    patient: "Sarah Johnson",
    action: "New appointment scheduled",
    timestamp: "2 hours ago",
    icon: Clock,
  },
  {
    id: 2,
    patient: "Michael Chen",
    action: "Completed visit",
    timestamp: "4 hours ago",
    icon: CheckCircle2,
  },
  {
    id: 3,
    patient: "Emily Rodriguez",
    action: "Medication updated",
    timestamp: "6 hours ago",
    icon: Activity,
  },
  {
    id: 4,
    patient: "James Wilson",
    action: "Flagged for follow-up",
    timestamp: "8 hours ago",
    icon: AlertCircle,
  },
];

export const departmentStats = [
  { name: "Cardiology", patients: 150, appointments: 85, growth: "+12%" },
  { name: "Neurology", patients: 120, appointments: 72, growth: "+8%" },
  { name: "Pediatrics", patients: 200, appointments: 110, growth: "+15%" },
  { name: "Orthopedics", patients: 180, appointments: 95, growth: "+10%" },
];

export const DEMO_NOTIFICATIONS = [
  {
    title: "New message",
    body: "You have a new message from Alex.",
    data: { url: "/messages" },
  },
  {
    title: "Deployment complete",
    body: "Production deployment finished successfully.",
    data: { url: "/deployments" },
  },
  {
    title: "Weekly summary",
    body: "Your weekly report is ready to view.",
    data: { url: "/reports" },
  },
];

export const SESSION_COOKIE_NAME = "__session";
export const SESSION_DURATION_MS = 60 * 60 * 24 * 1000;
