import { Patient } from "./types";

export const patientsData: Patient[] = [
  {
    id: "P001",
    name: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    phone: "+1 (555) 123-4567",
    age: 34,
    gender: "Female",
    status: "Active",
    lastVisit: "2024-03-10",
    nextAppointment: "2024-04-15",
    address: "123 Main St, City, State 12345",
    department: "Cardiology",
    conditions: ["Hypertension", "Diabetes"],
    medications: ["Lisinopril", "Metformin"],
    bloodType: "O+",
  },
  {
    id: "P002",
    name: "Michael Chen",
    email: "michael.chen@email.com",
    phone: "+1 (555) 234-5678",
    age: 45,
    gender: "Male",
    status: "Active",
    lastVisit: "2024-03-12",
    nextAppointment: "2024-03-25",
    address: "456 Oak Ave, City, State 12345",
    department: "Neurology",
    conditions: ["Migraines"],
    medications: ["Sumatriptan", "Propranolol"],
    bloodType: "A+",
  },
  {
    id: "P003",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@email.com",
    phone: "+1 (555) 345-6789",
    age: 28,
    gender: "Female",
    status: "Active",
    lastVisit: "2024-03-08",
    nextAppointment: "2024-04-01",
    address: "789 Pine Rd, City, State 12345",
    department: "Pediatrics",
    conditions: ["Asthma"],
    medications: ["Albuterol"],
    bloodType: "B+",
  },
  {
    id: "P004",
    name: "James Wilson",
    email: "james.wilson@email.com",
    phone: "+1 (555) 456-7890",
    age: 52,
    gender: "Male",
    status: "At Risk",
    lastVisit: "2024-02-28",
    nextAppointment: "2024-03-22",
    address: "321 Elm St, City, State 12345",
    department: "Orthopedics",
    conditions: ["Arthritis", "Back Pain"],
    medications: ["Ibuprofen", "Gabapentin"],
    bloodType: "A-",
  },
  {
    id: "P005",
    name: "Jessica Davis",
    email: "jessica.davis@email.com",
    phone: "+1 (555) 567-8901",
    age: 38,
    gender: "Female",
    status: "Active",
    lastVisit: "2024-03-11",
    nextAppointment: "2024-03-28",
    address: "654 Maple Dr, City, State 12345",
    department: "Dermatology",
    conditions: ["Eczema"],
    medications: ["Hydrocortisone"],
    bloodType: "O-",
  },
  {
    id: "P006",
    name: "Robert Martinez",
    email: "robert.martinez@email.com",
    phone: "+1 (555) 678-9012",
    age: 55,
    gender: "Male",
    status: "Inactive",
    lastVisit: "2024-01-15",
    nextAppointment: "2024-04-10",
    address: "987 Cedar Ln, City, State 12345",
    department: "Cardiology",
    conditions: ["High Cholesterol"],
    medications: ["Atorvastatin"],
    bloodType: "B-",
  },
  {
    id: "P007",
    name: "Amanda Brown",
    email: "amanda.brown@email.com",
    phone: "+1 (555) 789-0123",
    age: 31,
    gender: "Female",
    status: "Active",
    lastVisit: "2024-03-09",
    nextAppointment: "2024-03-23",
    address: "147 Birch Way, City, State 12345",
    department: "Neurology",
    conditions: [],
    medications: ["Vitamins"],
    bloodType: "AB+",
  },
  {
    id: "P008",
    name: "Christopher Lee",
    email: "christopher.lee@email.com",
    phone: "+1 (555) 890-1234",
    age: 42,
    gender: "Male",
    status: "Active",
    lastVisit: "2024-03-13",
    nextAppointment: "2024-04-05",
    address: "258 Spruce St, City, State 12345",
    department: "Orthopedics",
    conditions: ["Knee Pain"],
    medications: ["Physical Therapy"],
    bloodType: "O+",
  },
];
